# NOTE: update this with your service name
service: forum-app-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:121512594318:table/forum"
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  environment:
    tableName: userposts

functions:
  create:
    handler: create_post.main
    events:
      - http:
          path: forum
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: get_post.main
    events:
      - http:
          path: forum/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: list_posts.main
    events:
      - http:
          path: forum
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: update_post.main
    events:
      - http:
          path: forum/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: delete_post.main
    events:
      - http:
          path: forum/{id}
          method: delete
          cors: true
          authorizer: aws_iam

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
