service: forum-app-ext-database

custom:
  stage: ${opt:stage, self:provider.stage}
  tableNamePosts: ${self:custom.stage}-ext-posts
  tableNameComments: ${self:custom.stage}-ext-comments

provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.tableNamePosts}
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - AttributeName: postId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    CommentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameComments}
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
          - AttributeName: commentId
            AttributeType: S
        KeySchema:
          - AttributeName: postId
            KeyType: RANGE
          - AttributeName: commentId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

  Outputs:
    PostsTableArn:
      Value:
        Fn::GetAtt:
          - PostsTable
          - Arn
        Export:
          Name: ${self:custom.stage}-ExtPostsTableArn
    CommentsTableArn:
      Value:
        Fn::GetAtt:
          - CommentsTable
          - Arn
        Export:
          Name: ${self:custom.stage}-ExtCommentsTableArn
