# NOTE: update this with your service name
service: post-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom: ${file(../../serverless.common.yml):custom}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}
    publicKeyURL: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_LBYlIME5a/.well-known/jwks.json
    # tableNameUserPosts: userposts
    # tableNameComments: usercomments
    # tableNameCommentLikes: commentLikes
    # tableNamePostLikes: userlikes
    # bucketName: niro-forum-user-uploads
    # avatarFileName: _user_avatar

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::ImportValue': ${self:custom.resourcesStage}-ExtPostsTableArn
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:PutObject
      Resource:
        - 'Fn::ImportValue': ${self:custom.resourcesStage}-ExtAttachmentsBucketArn


functions:
  create:
    handler: create_post.main
    events:
      - http:
          path: forum
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: get_post.main
    events:
      - http:
          path: forum/{postId}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: list_posts.main
    events:
      - http:
          path: forum
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: update_post.main
    events:
      - http:
          path: forum/{postId}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: delete_post.main
    events:
      - http:
          path: forum/{postId}
          method: delete
          cors: true
          authorizer: aws_iam


resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}


- Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:custom.stage}-ExtApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
